source:         .
destination:    ./_site
plugins_dir:    ./_plugins
layouts_dir:    ./_layouts
pages_dir:      ./_pages
sass_path:      ./_compass
include:        ['.htaccess']
exclude:        ['./_docker', 'Gemfile', 'Gemfile.lock', 'README.md', 'Rakefile']
keep_files:     ['.git']
timezone:       nil
encoding:       utf-8
future:         true
show_drafts:    false
limit_posts:    0

permalink:      date
paginate:       10

markdown:       redcarpet
markdown_ext:   markdown,mkdown,mkdn,mkd,md

excerpt_separator: "\n\n\n"

curly_open:     "{"
curly_close:    "}"

url:            http://kiguino.com
title:          Personal blog by Konstantin Gredeskoul
description:    'Tales on Hardware, Software, Technology, DIY, Makers, Hacking, Life and more &mdash; by a veteran software engineer, CTO, inventor, hacker, mentor <a href="/professional/summary">Konstantin Gredeskoul</a>.'
author:
  name:       Konstantin Gredeskoul
  url:        https://twitter.com/kig

github_username: kigster
github_repos:
  - ventable
  - laser-cutter
  - occupus

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

github:
  repo:      https://github.com/kigster/kiguino.github.io
