source:         .
destination:    ./_site
plugins:        ./_plugins
layouts:        ./_layouts
include:        ['.htaccess']
exclude:        []
keep_files:     ['.git','.svn']
gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

timezone:       nil
encoding:       utf-8
future:         true
show_drafts:    false
limit_posts:    0

permalink:      date
paginate:       5

highlighter:    pygments
markdown:       redcarpet
markdown_ext:   markdown,mkdown,mkdn,mkd,md

excerpt_separator: "\n\n\n"

curly_open:     "{"
curly_close:    "}"

host:           0.0.0.0
port:           4000
baseurl:        /
url:            http://kiguino.com
title:          KIGUINO
description:    'Tales on Hardware, Software, Technology, DIY, Makers, Hacking, Life and more &mdash; by a veteran software engineer, CTO, inventor, hacker, mentor <a href="https://twitter.com/kig">Konstantin Gredeskoul</a>.'
author:      
  name:       Konstantin Gredeskoul
  url:        https://twitter.com/kig

github_username: kigster
github_repos:
  - ventable
  - laser-cutter
  - occupus


redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

github:
  repo:      https://github.com/kigster/kiguino.github.io
