#!/usr/bin/env bash

hook() {
  file=$1
  [[ -x "$file" ]] && source $file
}

function local_deploy() { 
  project_home=$(dirname $0)
  cd $project_home && pwd

  if [[ "$(git status --short | wc -l)" -ne 0 ]]; then
    printf "Local repo is not clean, please fix.\n"
    return
  fi

  git reset --hard
  git pull --rebase

  eval "$(rbenv init -)"
  gem install bundler --conservative
  hook "before-bundle"
  bundle
  hook "before-build"
  bundle exec jekyll build
  find . -type d -exec chmod 755 {} \;
  find . -type f -exec chmod o+r {} \;
  hook "after-build"
  cd -
}

function remote_deploy() {
  ssh kig.re -l kig 'bash -l -c "cd workspace/kig.re && source ~/.bashrc && ./deploy"'
}

if [[ "$(uname -s)" == "Darwin" ]]; then
  remote_deploy
else
  local_deploy
fi

