#!/usr/bin/env bash
hook() {
  file=$1
  [[ -x "$file" ]] && source $file
}

project_home=$(dirname $0)
cd $project_home && pwd
eval "$(rbenv init .)"
git reset --hard
git pull --rebase
hook "before-bundle"
bundle
hook "before-build"
bundle exec jekyll build
find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod o+r {} \;
hook "after-build"
cd -
