source 'https://rubygems.org'
gem 'jekyll'
gem 'colored2'
gem 'rake'
gem 'nokogiri'
group :jekyll_plugins do
  gem 'redcarpet'
  gem 'jekyll-coffeescript'
  gem 'jekyll-watch'
  gem 'jekyll-feed'
  gem 'jekyll-assets'
  gem 'jekyll-paginate'
  gem 'jekyll-gist'
  gem 'jekyll-compass'
end
