source:         .
destination:    ./_site
plugins_dir:    ./_plugins
layouts_dir:    ./_layouts
pages_dir:      ./_pages
sass_path:      ./_compass
include:        ['.htaccess']
exclude:        ['./_docker', 'Gemfile', 'Gemfile.lock', 'README.md', 'Rakefile']
keep_files:     ['.git']
timezone:       nil
encoding:       utf-8
future:         true
show_drafts:    false
limit_posts:    0

permalink:      date
paginate:       5

markdown:       redcarpet
markdown_ext:   markdown,mkdown,mkdn,mkd,md

excerpt_separator: "\n\n\n"

curly_open:     "{"
curly_close:    "}"

baseurl:       ''
url:            http://kig.re
title:          by Konstantin Gredeskoul (@kig)
description:    'Stories from the frontlines of software engineers, hardware tinkering, general technology, DIY and makers, hacking and about life in general &mdash; by a veteran software engineer, three-times CTO, inventor, hacker, mentor <a href="/about">Konstantin Gredeskoul</a>.'
author:
  name:       Konstantin Gredeskoul
  url:        https://twitter.com/kig

github_username: kigster
github_repos:
  - ventable
  - laser-cutter
  - occupus

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

github:
  repo:      https://github.com/kigster

plugins:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-paginate
  - jekyll-compass
  - jekyll-assets
  - jekyll-toc

showToggleButton: false

docker:
  image:
    user: kigster
    name: kigre
  container:
    name: kigre
  dockerfile: nginx-src

jekyll-crosspost_to_medium:
  enabled: false
  status: public
  backdate: false
