:page-asciidoc: true
:page-author_id: 1
:page-layout: page
:page-liquid:
:page-image_url: '/assets/images/posts/kig/kig-2015-geekcamp-328x328.png'
:page-title: "About"
:page-add_to_menu: true
:page-asciidoc_toc: true


== About Konstantin

NOTICE: Please note that if you are interested in hiring Konstantin, please reach out via the contact info in his https://bit.ly/kig-resume[resume].

Konstantin is a type of software engineer who's been coding since he was an infant. Or so the legend goes ;) 

He worked across a range of Internet companies, as a Systems Architect, Lead Engineer, and, four separate times, a CTO. He loves both attending and speaking at tech conferences, and was invited to speak at https://www.youtube.com/watch?v=fd9i0GAzZI8[RubyConf Australia in 2015], and https://www.youtube.com/watch?v=9Hf8Bfvb3hE[PostgreSQL Silicon Valley] conference shortly thereafter.

Some Hightlights:

 * An avid open source contributor, Konstantin authored over https://rubygems.org/profiles/kigster[forty ruby gems] with nearly 20M downloads

 * His online presentations have been watched by more than quarter million people worldwide — https://slideshare.net/kigster[slideshare.net/kigster].

 * He writes a technology blog at https://kig.re/[kig.re], and actively contributes to libraries in C/C++, CMake, Arduino, Bash, as well as Chef.

 * He owns a small consulting firm https://reinvent.one[Reinvent.ONE], which has helped companies from Hired.com, to Shippo, Returnly, Homebase, Wanelo, and more.

More info — reach in his https://bit.ly/kig-resume[resume].
