title: Ramblings of a Techie — kig.re — Konstantin Gredeskoul
email: kig@reinvent.one
description: "This is a personal blog of Konstantin Gredeskoul — a former CTO, Ruby Expert, Loving of all things Scaling and Performance."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kig.re1.re/" # the base hostname & protocol for your site, e.g. http://example.com
logo_url: '/assets/images/site/logo.png'
facebook_username: kigster
github_username:  kigster
linkedin_username: kigster
twitter_username: kig

# Build settings
exclude:
  - "**/.DS_Store"
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - package.json
  - package-lock.json
  - gulpfile.js
  - lib/**/*
  - bin/**/*
  - node_modules/**/*
  - _old_posts
  - .git/**/*
  - .gitignore
  - .editorconfig
  - .idea/**/*
  - _vendor/**/*
  - _sass/**/*

sass:
  sass_dir: _sass

markdown: kramdown
markdown_ext: md

kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes:
  hard_wrap: false
  footnote_nr: 1
  show_warnings: true

timezone: "America/Los_Angeles"
highlighter: rouge
permalink: /:year/:month/:day/:title:output_ext

theme: minima
plugins:
  - jekyll-archives
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-asciidoc

###################################################################
# Site configuration for the Jekyll 2 Pagination Gem
###################################################################
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/pages/:num/' # Pages are simple html files
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  #extension: 'html'
  indexpage: 'index'

autopages:
  enabled: true
  categories:
    layouts:
      - 'category.html'
    title: 'Category -  :cat'
    permalink: '/category/:cat'
  collections:
    layouts:
      - 'category.html'
    title: ' :coll' # :coll is replaced by the collection name
    permalink: '/:coll/'
  tags:
    layouts:
      - 'tag_page.html'
    title: '#:tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

collections:
  authors:
    title: Authors
    output: true
    permalink: /authors/:path/

feed:
  collections:
    posts:
      path: "/index.xml"
