# frozen_string_literal: true

ENV['RUBYOPT'] = 'W0'

require 'colored2'
require 'rake'
require 'erb'
require 'yaml'
# require 'hashie/mash'

require_relative '../lib/task_helper'

load '../lib/tasks/deploy.rake'
load '../lib/tasks/docker.rake'
load '../lib/tasks/jekyll.rake'

task default: 'jekyll:preview'

